services:
  # Aplicación Next.js para desarrollo
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@admin-souvenir-nodejs-db-1:5432/souvenirbd
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: 51e7ec2e32a2dfa8073457eec56b62d3e03b1fd5c211dfec40fc0507fc041601
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default
      - admin-souvenir-nodejs_default
    command: >
      sh -c "
        echo 'Esperando base de datos...' &&
        echo 'Iniciando aplicación...' &&
        npm run dev
      "

networks:
  admin-souvenir-nodejs_default:
    external: true

volumes:
  postgres_data:
